### ISSUE TITLE
how to using item2

### ISSUE THREAD

**Issue by 2015WUJI01** [yinan-c/alfred-homebrew#1]
this is a great workflow!!

It uses default terminal, how to switch to item2?

**Comment by yinan-c** [comment]
Hi @2015WUJI01, thank you, I'm glad you find it useful!

This workflow uses the default terminal set in Alfred. You can change it to iTerm by customizing the setting: In Alfred setting, Go to `Features - Terminal`, in `Application` select `Custom`, and then you can write down the following AppleScript:

```
on alfred_script(q)
	tell application "iTerm"
		activate
		tell current window
			create tab with default profile
			tell current session
				write text q
			end tell
		end tell
	end tell
end alfred_script
```
This will change all terminal actions in Alfred to open in iTerm.
<img width="1392" alt="CleanShot 2023-06-07 at 09 45 30@2x" src="https://github.com/yinan-c/alfred-homebrew/assets/95043151/786b4fca-abb6-42b0-8ba1-7458168442fe">
